# Descriptive Statistics

In [1]:
#imports
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

from collections import Counter, defaultdict

In [2]:
#directory locations
current_directory = os.getcwd()
parent_directory = os.path.dirname(current_directory)
processed_folder = parent_directory + '/data/wine-com/processed/'

### Load Data

In [3]:
df = pd.read_csv(processed_folder + '1677290348.7771397.txt', sep = '|')

In [4]:
df.head()

,product_url,product_name,product_variety,product_origin,product_family,user_avg_rating,user_rating_count,winemaker_description,reviewer_name,reviewer_rating,reviewer_text
0,https://www.wine.com/product/scott-harvey-moun...,Scott Harvey Mountain Selection Zinfandel 2019,Zinfandel,"from Amador, Sierra Foothills, California",Red Wine,4.3,39,30 year old px shows intense ebony color dense...,Wine Enthusiast,93,singed black sesame rye buckwheat honey black ...
1,https://www.wine.com/product/scott-harvey-moun...,Scott Harvey Mountain Selection Zinfandel 2019,Zinfandel,"from Amador, Sierra Foothills, California",Red Wine,4.3,39,30 year old px shows intense ebony color dense...,Wilfred Wong of Wine.com,90,singed black sesame rye buckwheat honey black ...
2,https://www.wine.com/product/viticcio-chianti-...,Viticcio Chianti Classico Riserva 2017,Sangiovese,"from Chianti Classico, Chianti, Tuscany, Italy",Red Wine,5.0,5,30 year old px shows intense ebony color dense...,Wine Spectator,94,singed black sesame rye buckwheat honey black ...
3,https://www.wine.com/product/viticcio-chianti-...,Viticcio Chianti Classico Riserva 2017,Sangiovese,"from Chianti Classico, Chianti, Tuscany, Italy",Red Wine,5.0,5,30 year old px shows intense ebony color dense...,James Suckling,92,singed black sesame rye buckwheat honey black ...
4,https://www.wine.com/product/adriano-marco-e-v...,Adriano Marco e Vittorio Sanadaive Barbaresco ...,Nebbiolo,"from Barbaresco, Piedmont, Italy",Red Wine,4.9,5,30 year old px shows intense ebony color dense...,Wine Enthusiast,94,singed black sesame rye buckwheat honey black ...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7293 entries, 0 to 7292
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_url            7293 non-null   object
 1   product_name           7293 non-null   object
 2   product_variety        7293 non-null   object
 3   product_origin         7293 non-null   object
 4   product_family         7293 non-null   object
 5   user_avg_rating        7293 non-null   float64
 6   user_rating_count      7293 non-null   int64
 7   winemaker_description  7293 non-null   object
 8   reviewer_name          7293 non-null   object
 9   reviewer_rating        7293 non-null   int64
 10  reviewer_text          7293 non-null   object
dtypes: float64(1), int64(2), object(8)
memory usage: 626.9+ KB

### Basic Descriptive Statistics

In [6]:
df.describe()

       user_avg_rating  user_rating_count  reviewer_rating
count      7293.000000        7293.000000      7293.000000
mean          1.644646          18.807212        92.056218
std           2.037469          80.586093         1.918561
min           0.000000           0.000000        88.000000
25%           0.000000           0.000000        91.000000
50%           0.000000           0.000000        92.000000
75%           3.900000          12.000000        93.000000
max           5.000000        1883.000000       100.000000

Of note, this dataset contains 13,042 unqiue products across 127 vartietals and 8 distinct wine types. Descriptions provided by wine makers siginficantly outnumber the quantity of professional reviews.

To ensure that sufficient coverage is present across wine types, the above statistics will be recomputed for each unique wine type.

In [7]:
df.groupby('product_family').describe()

                        user_avg_rating                                     \
                                  count      mean       std  min  25%  50%
product_family
Champagne & Sparkling             609.0  2.551724  1.985267  0.0  0.0  3.8
Dessert, Sherry, & Port           421.0  2.919952  2.010409  0.0  0.0  4.1
Red Wine                         4250.0  1.481247  1.996475  0.0  0.0  0.0
Rosé Wine                          51.0  1.562745  2.067168  0.0  0.0  0.0
White Wine                       1962.0  1.445515  1.975127  0.0  0.0  0.0

                                   user_rating_count             ...        \
                          75%  max             count       mean  ...   75%
product_family                                                   ...
Champagne & Sparkling    4.10  5.0             609.0  86.065681  ...  66.0
Dessert, Sherry, & Port  4.40  5.0             421.0  56.945368  ...  55.0
Red Wine                 3.80  5.0            4250.0  10.054824  ...  10.0
Rosé Wine                3.95  5.0              51.0   6.098039  ...   9.5
White Wine               3.80  5.0            1962.0   9.036188  ...   9.0

                                reviewer_rating                             \
                            max           count       mean       std   min
product_family
Champagne & Sparkling    1883.0           609.0  91.399015  1.751897  88.0
Dessert, Sherry, & Port   619.0           421.0  92.529691  2.190281  89.0
Red Wine                 1846.0          4250.0  92.166824  1.872917  88.0
Rosé Wine                  36.0            51.0  90.980392  1.449002  88.0
White Wine               1013.0          1962.0  91.946993  1.950233  88.0


                          25%   50%   75%    max
product_family
Champagne & Sparkling    90.0  91.0  92.0   98.0
Dessert, Sherry, & Port  91.0  92.0  94.0   99.0
Red Wine                 91.0  92.0  93.0  100.0
Rosé Wine                90.0  91.0  92.0   96.0
White Wine               90.0  92.0  93.0  100.0

[5 rows x 24 columns]

Interestingly, there exists labels that don't relate to the wines family. Given the relative size of these record groups, it may be worth relabeling or dropping these groups. 

Another aspect worth noting is that unless the text bodies of 'description' and 'review' proven to diverge significantly, predictive models would likely benefit from combining these fields into a single corpus.

### 'Description' Analysis

In [8]:
#lifted from homwork
def descriptive_stats(tokens, num_tokens = 10, verbose=True):
    tokens_str = tokens.astype(str)
    joined_series_tokens = ' '.join(tokens_str)
    tokens = joined_series_tokens.split()
    
    num_tokens = len(tokens)
    num_unique_tokens = len(set(tokens))
    lexical_diversity = num_unique_tokens/num_tokens #defined as unique tokens to the total number of words
    num_characters = sum(len(i) for i in tokens)
    
    if verbose :        
        print(f"There are {num_tokens} tokens in the data.")
        print(f"There are {num_unique_tokens} unique tokens in the data.")
        print(f"There are {num_characters} characters in the data.")
        print(f"The lexical diversity is {lexical_diversity:.3f} in the data.")
    
        # find five most common tokens
        counter = Counter(tokens)
        n_most_common_tokens = counter.most_common(10)
        print(f"The {num_tokens} most common tokens were:\n{n_most_common_tokens}")
        
    return([num_tokens, num_unique_tokens,
            lexical_diversity,
            num_characters])

In [9]:
unique_wines = df['product_family'].unique()

for wine_types in unique_wines:
    tmp = df[df['product_family'] == wine_types]
    print(f'{wine_types} Outputs\n')
    descriptive_stats(tmp['winemaker_description'])
    print('\n')

Red Wine Outputs

There are 148750 tokens in the data.
There are 34 unique tokens in the data.
There are 828750 characters in the data.
The lexical diversity is 0.000 in the data.
The 148750 most common tokens were:
[('fruit', 8500), ('30', 4250), ('year', 4250), ('old', 4250), ('px', 4250), ('shows', 4250), ('intense', 4250), ('ebony', 4250), ('color', 4250), ('dense', 4250)]


White Wine Outputs

There are 68670 tokens in the data.
There are 34 unique tokens in the data.
There are 382590 characters in the data.
The lexical diversity is 0.000 in the data.
The 68670 most common tokens were:
[('fruit', 3924), ('30', 1962), ('year', 1962), ('old', 1962), ('px', 1962), ('shows', 1962), ('intense', 1962), ('ebony', 1962), ('color', 1962), ('dense', 1962)]


Champagne & Sparkling Outputs

There are 21315 tokens in the data.
There are 34 unique tokens in the data.
There are 118755 characters in the data.
The lexical diversity is 0.002 in the data.
The 21315 most common tokens were:
[('fruit', 1218), ('30', 609), ('year', 609), ('old', 609), ('px', 609), ('shows', 609), ('intense', 609), ('ebony', 609), ('color', 609), ('dense', 609)]


Rosé Wine Outputs

There are 1785 tokens in the data.
There are 34 unique tokens in the data.
There are 9945 characters in the data.
The lexical diversity is 0.019 in the data.
The 1785 most common tokens were:
[('fruit', 102), ('30', 51), ('year', 51), ('old', 51), ('px', 51), ('shows', 51), ('intense', 51), ('ebony', 51), ('color', 51), ('dense', 51)]


Dessert, Sherry, & Port Outputs

There are 14735 tokens in the data.
There are 34 unique tokens in the data.
There are 82095 characters in the data.
The lexical diversity is 0.002 in the data.
The 14735 most common tokens were:
[('fruit', 842), ('30', 421), ('year', 421), ('old', 421), ('px', 421), ('shows', 421), ('intense', 421), ('ebony', 421), ('color', 421), ('dense', 421)]

### 'Review' Analysis

In [10]:
for wine_types in unique_wines:
    tmp = df[df['product_family'] == wine_types]
    print(f'{wine_types} Outputs\n')
    descriptive_stats(tmp['critical_reviews'])
    print('\n')

Red Wine Outputs

KeyError: 'critical_reviews'

Based on the top 10 most common terms, joining the fields 'description' and 'reviews' is a reasonable proposal.

### Description Lengths

In [ ]:
df['description_length'] = df['description'].str.len()

In [ ]:
fig = plt.figure(figsize=(10, 10))
df.groupby('type')['description_length'].plot(kind="hist",density=True,alpha=0.5,legend=True)
plt.show()

### Review Lengths

In [ ]:
df['review_length'] = df['reviews'].str.len()

In [ ]:
fig = plt.figure(figsize=(10, 10))
df.groupby('type')['review_length'].plot(kind="hist", 
                                         density=True, 
                                         alpha=0.5,
                                         legend=True)
plt.show()

Interestingly, the distrbution of description and review lengths appear to follow different distribution types.

### Unique Tokens

Given that there are multiple labels in the set, we will modify a function from prior homework to perform OvR comparisons for terms unique to each wine type.

In [ ]:
#modified from homework to be generally useful
def unique_tokens(df, comparison_column, split_column, n_total_corpora, n_top_terms):
    unique_splits = df[split_column].unique()
    for split in unique_splits:
        #perform split
        corpus_1 = df[df[split_column] == split]
        corpus_2 = df[df[split_column] != split]
        #preprocess
        corpus_1_str = corpus_1[comparison_column].astype(str)
        corpus_2_str = corpus_2[comparison_column].astype(str)
        corpus_1_joined = ' '.join(corpus_1_str)
        corpus_2_joined = ' '.join(corpus_2_str)
        corpus_1_tokens = corpus_1_joined.split()
        corpus_2_tokens = corpus_2_joined.split()
        #generate token counts for each corpora
        corpus_1_counts = Counter(corpus_1_tokens)
        corpus_2_counts = Counter(corpus_2_tokens)
        #write to dataframe
        corpus_1_df = pd.DataFrame(data = corpus_1_counts.values(), 
                               index = corpus_1_counts.keys(),
                               columns = ['1_word_counts'])
        corpus_2_df = pd.DataFrame(data = corpus_2_counts.values(), 
                               index = corpus_2_counts.keys(),
                               columns = ['2_word_counts'])
        #join dataframes
        corpus_df = corpus_1_df.merge(corpus_2_df, 
                                      how = 'outer',
                                      left_index = True, 
                                      right_index= True)
        #impute null values with 0
        corpus_df = corpus_df.fillna(0)
        #filtering corpora to required  relevance
        corpus_df = corpus_df[corpus_df['1_word_counts'] >= n_total_corpora]
        corpus_df = corpus_df[corpus_df['2_word_counts'] >= n_total_corpora]
        #calculate term concentrations
        corpus_df['1_concentrations'] = corpus_df['1_word_counts']/len(corpus_1)
        corpus_df['2_concentrations'] = corpus_df['2_word_counts']/len(corpus_2)
        #generate term ratio
        corpus_df['term_ratio'] = corpus_df['1_concentrations']/corpus_df['2_concentrations']
        #sort ratios
        corpus_df = corpus_df.sort_values(by = ['term_ratio'], ascending = False)
        #generate outputs
        corpus_1_top_n = corpus_df['term_ratio'].head(n_top_terms).to_dict()
        #print outputs
        print(f'Unique tokens observed for the label {split}:\n')
        print(corpus_1_top_n)
        print(f'\n')

### Description Unique Terms

In [ ]:
unique_tokens(df, 
              comparison_column = 'description', 
              split_column = 'type',
              n_total_corpora = 5,
              n_top_terms = 10)

In [ ]:
unique_tokens(df, 
              comparison_column = 'reviews', 
              split_column = 'type',
              n_total_corpora = 5,
              n_top_terms = 10)

Observing the unique terms produced in the OvR analysis does produce an interesting insight that the reviews tend to focus more on the tasting notes of the product. Depending on the predictive application, this dynamic could be useful for informing the final model inputs.